listen_addr               = "0.0.0.0:7001"
data_dir                  = "/var/lib/postgresql/data"
postgres_host             = "pg-replica-1"
postgres_port             = 5432
postgres_user             = "postgres"
postgres_password         = "test"
postgres_dbname           = "postgres"
heartbeat_timeout_seconds = 10
fence_timeout_seconds     = 30
pg_ctl_path               = "/usr/lib/postgresql/15/bin/pg_ctl"
